config/routes.rb
Rails.application.routes.draw do
  resources :opportunities

  devise_for :users
  root 'static_pages#home'
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  validates :customer,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :set_opportunity, only: [:show, :edit, :update, :destroy]

  def index
    @opportunities = Opportunity.all
  end

  def new
    @opportunity = Opportunity.new
  end

  def create
    @opportunity = Opportunity.new(opportunity_params)
    if @opportunity.save
      redirect_to(root_path)
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end

  def update
    if @opportunity.update_attributes(opportunity_params)
      redirect_to @opportunity
    else
      render 'edit'
    end
  end

  def destroy
    Opportunity.find(params[:id]).destroy
    redirect_to opportunities_url
  end


end

private
    def set_opportunity
      @opportunity = Opportunity.find(params[:id])
    end

    def opportunity_params
      params.require(:opportunity).permit(
        :customer,
        :partner,
        :subject,
        :summary,
        :initial_cost,
        :monthly_cost,
        :expected_date_of_purchase_order,
        :schedule,
        :sales_staff,
        :technical_staff,
        :remarks
      )
    end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple SFA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <%= link_to 'Simple SFA', root_path, class: 'navbar-brand' %>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to current_user.email, root_path %></li>
                <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'サインアップ', new_user_registration_path %></li>
                <li><%= link_to 'ログイン', new_user_session_path %></li>
            <% end %>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="active"><%= link_to '商談一覧', opportunities_path %></li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Analytics</a></li>
                    <li><a href="#">Export</a></li>
                </ul>
            </div>

            <div class="col-md-10 col-md-offset-2 main">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>

                <%= yield %>
            </div>

        </div>
    </div>

</body>
</html>

app/views/opportunities/_form.html.erb
<%= bootstrap_form_for(@opportunity) do |f| %>

<%= f.text_field :customer,                        label: '顧客名' %>
<%= f.text_field :partner,                         label: 'パートナー名' %>
<%= f.text_field :subject,                         label: '案件名' %>
<%= f.text_area  :summary,                         label: '概要' %>
<%= f.text_field :initial_cost,                    label: '初期費用' %>
<%= f.text_field :monthly_cost,                    label: '月次費用' %>
<%= f.text_field :expected_date_of_purchase_order, label: '受注予定日' %>
<%= f.text_area  :schedule,                        label: 'スケジュール' %>
<%= f.text_field :sales_staff,                     label: '営業担当' %>
<%= f.text_field :technical_staff,                 label: '技術担当' %>
<%= f.text_area  :remarks,                         label: '備考' %>

<%= f.submit '登録', class: "btn btn-large btn-primary" %>
<% end %>

app/views/opportunities/edit.html.erb
<h1>商談編集</h1>

<%= render 'form' %>

app/views/opportunities/index.html.erb
<h1>商談一覧</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>顧客名</th>
      <th>案件名</th>
      <th>初期費用</th>
      <th>月次費用</th>
      <th>受注予定日</th>
      <th>営業担当</th>
      <th>技術担当</th>
    </tr>
  </thead>
  <tbody>
  <% @opportunities.each do |opportunity| %>
    <tr>
      <td><%= truncate opportunity.customer, :length => 10 %></td>
      <td><%= link_to truncate(opportunity.subject, :length => 15), opportunity %></td>      
      <td><%= number_to_currency opportunity.initial_cost, :unit => "￥", precision: 0 %></td>      
      <td><%= number_to_currency opportunity.monthly_cost, :unit => "￥", precision: 0 %></td>      
      <td><%= opportunity.expected_date_of_purchase_order %></td>      
      <td><%= opportunity.sales_staff %></td>      
      <td><%= opportunity.technical_staff %></td>      
    </tr>
  <% end %>
  </tbody>
</table>

app/views/opportunities/new.html.erb
<h1>商談新規登録</h1>

<%= render 'form' %>

app/views/opportunities/show.html.erb
<%= link_to "編集", edit_opportunity_path, class: "btn btn-lg btn-primary" %>
<hr class="featurette-divider">
<h4>顧客名</h4>
<p><%= @opportunity.customer %></p>
<hr class="featurette-divider">
<h4>パートナー名</h4>
<p><%= @opportunity.partner %></p>
<hr class="featurette-divider">
<h4>案件名</h4>
<p><%= @opportunity.subject %></p>
<hr class="featurette-divider">
<h4>概要</h4>
<p><%= simple_format @opportunity.summary %></p>
<hr class="featurette-divider">
<h4>初期費用</h4>
<p><%= number_to_currency @opportunity.initial_cost, :unit => "￥", precision: 0 %></p>
<hr class="featurette-divider">
<h4>月次費用</h4>
<p><%= number_to_currency @opportunity.monthly_cost, :unit => "￥", precision: 0 %></p>
<hr class="featurette-divider">
<h4>受注予定日</h4>
<p><%= @opportunity.expected_date_of_purchase_order %></p>
<hr class="featurette-divider">
<h4>スケジュール</h4>
<p><%= simple_format @opportunity.schedule %></p>
<hr class="featurette-divider">
<h4>営業担当</h4>
<p><%= @opportunity.sales_staff %></p>
<hr class="featurette-divider">
<h4>技術担当</h4>
<p><%= @opportunity.technical_staff %></p>
<hr class="featurette-divider">
<h4>備考</h4>
<p><%= simple_format @opportunity.remarks %></p>
<hr class="featurette-divider">
<%= link_to "削除", @opportunity, method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-lg btn-danger" %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<% if user_signed_in? %>
    <p>ようこそ <%= current_user.email %></p>
<% else %>
    <p>未ログイン</p>
<% end %>
<%= link_to '商談登録', new_opportunity_path %>